export type Question = { q: string; options: [string, string, string]; correct: 0 | 1 | 2 };
export type TestKey = "veterinar" | "kovar" | "trener";

export const TEST_META: Record<TestKey, { title: string; photo: string; alt: string }> = {
  veterinar: {
    title: "Veterinář",
    photo: "https://images.unsplash.com/photo-1598715685267-0f45367d8071?w=1200",
    alt: "Veterinář pracující s koněm",
  },
  kovar: {
    title: "Kovář",
    photo: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=1200",
    alt: "Kovář při práci",
  },
  trener: {
    title: "Trenér",
    photo: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=1200",
    alt: "Trenér dostihových koní",
  },
};

export const QUESTIONS: Record<TestKey, Question[]> = {
  veterinar: [
    { q: "Jaká je normální tělesná teplota koně?", options: ["37,5–38,5 °C", "36,0–36,5 °C", "39,5–40,5 °C"], correct: 0 },
    { q: "Jaká je průměrná délka březosti klisny?", options: ["7 měsíců", "11 měsíců", "14 měsíců"], correct: 1 },
    { q: "Kde se měří puls u koně nejčastěji?", options: ["Na hrudní kosti", "Na dolní čelisti", "Na uších"], correct: 1 },
    { q: "Jaká je průměrná srdeční frekvence dospělého koně v klidu?", options: ["28–44 tepů za minutu", "60–80 tepů za minutu", "100–120 tepů za minutu"], correct: 0 },
    { q: "Jak se nazývá onemocnění kopyt způsobené zánětem škáry?", options: ["Laminitida", "Kolika", "Artritida"], correct: 0 },
    { q: "Co je to „kolika“ u koní?", options: ["Zánět plic", "Porucha trávicího traktu s bolestí břicha", "Onemocnění kloubů"], correct: 1 },
    { q: "Jaký je průměrný věk dožití koně?", options: ["10–12 let", "15–20 let", "25–30 let"], correct: 2 },
    { q: "Jak se nazývá vakcinace proti tetanu u koní?", options: ["Antitetanový toxoid", "Antibiotická kúra", "Sérum proti chřipce"], correct: 0 },
    { q: "Kdy by se měly pravidelně kontrolovat zuby koně?", options: ["Jednou za 10 let", "Každý rok", "Nikdy"], correct: 1 },
    { q: "Co je to „strangles“ (mor koní)?", options: ["Respirační onemocnění způsobené bakteriemi", "Virové onemocnění jater", "Kožní plísňová infekce"], correct: 0 },
    { q: "Jak se podává většina odčervovacích přípravků koním?", options: ["Injekčně do svalu", "Pastou do tlamy", "Přes kopyto"], correct: 1 },
    { q: "Jaké je nejčastější onemocnění dýchacího aparátu koní?", options: ["COPD (chronická obstrukční plicní nemoc)", "Laminitida", "Artróza"], correct: 0 },
    { q: "Jaká je hlavní příčina nadměrného opotřebení zubů u koní?", options: ["Tvrdé krmivo a nepravidelná kontrola", "Nedostatek vitamínu C", "Infekce dásní"], correct: 0 },
    { q: "Jak často by se měl kůň odčervovat?", options: ["Každé 2 roky", "Podle plánu veterináře, obvykle 3–4× ročně", "Nikdy, pokud nevykazuje příznaky"], correct: 1 },
    { q: "Jak se nazývá metoda prevence onemocnění kopyt u koní?", options: ["Pravidelné seřezávání a čištění kopyt", "Podávání antibiotik", "Podávání soli do vody"], correct: 0 },
    { q: "Jak se nazývá stav, kdy má kůň zvýšenou teplotu, kašel a výtok z nosu?", options: ["Koňská chřipka", "Kolika", "Laminitida"], correct: 0 },
    { q: "Jaká je nejčastější příčina koliky u koní?", options: ["Srdeční selhání", "Porucha trávicího systému (zácpa, plynatost, zauzlení střev)", "Nedostatek spánku"], correct: 1 },
    { q: "Jak poznáme dehydrataci u koně?", options: ["Test kožní řasy a suché sliznice", "Změna barvy srsti", "Delší spánek"], correct: 0 },
    { q: "Jak se říká základnímu vyšetření prováděnému veterinářem?", options: ["Diagnóza", "Klinické vyšetření", "Očkování"], correct: 1 },
    { q: "Jaký je účel vakcinace proti koňské chřipce?", options: ["Zlepšení trávení", "Prevence respirační infekce", "Zvýšení výkonnosti"], correct: 1 },
  ],
  kovar: [
    { q: "Jaký je hlavní účel kování koní?", options: ["Ozdoba kopyta", "Ochrana kopyta před opotřebením", "Zvýšení rychlosti běhu"], correct: 1 },
    { q: "Z jakého materiálu se tradičně vyrábí podkovy?", options: ["Plast", "Dřevo", "Ocel"], correct: 2 },
    { q: "Jak často se obvykle mění podkovy u aktivně využívaného koně?", options: ["Každý týden", "Každých 6–8 týdnů", "Jednou ročně"], correct: 1 },
    { q: "Jak se jmenuje nástroj pro vytažení starých podkov?", options: ["Kleště na podkováky", "Kopytní nůž", "Raspa"], correct: 0 },
    { q: "Co je hlavním znakem přerostlého kopyta?", options: ["Měkká stěna", "Praskliny a deformace", "Ztráta barvy"], correct: 1 },
    { q: "Jaký je účel „raspy“?", options: ["Odstranění hřebíků", "Vyrovnání a úprava kopyta", "Zkrácení žíní"], correct: 1 },
    { q: "Jaký je správný název pro osobu, která odborně ková koně?", options: ["Sedlář", "Podkovář", "Kovárník"], correct: 1 },
    { q: "Co je to „kopytní střelka“?", options: ["Část podkovy", "Trojúhelníkovitá část kopyta", "Speciální druh hřebu"], correct: 1 },
    { q: "Proč se používají podkováky (hřeby)?", options: ["K upevnění podkovy na kopyto", "Ke zpevnění stěny kopyta", "K odvádění vlhkosti"], correct: 0 },
    { q: "Jak se nazývá metoda, kdy kůň chodí bez podkov?", options: ["Barefoot", "Lightfoot", "Freehoof"], correct: 0 },
    { q: "Jaký je hlavní důvod pro ortopedické podkovy?", options: ["Lepší estetika", "Léčba a podpora kopyta při problémech", "Rychlejší běh"], correct: 1 },
    { q: "Jaký je účel hliníkových podkov?", options: ["Jsou lehčí pro sportovní koně", "Jsou levnější než ocelové", "Chrání lépe proti vlhku"], correct: 0 },
    { q: "Co se používá k vyčištění kopyta před kováním?", options: ["Kartáč na srst", "Kopytní háček", "Sedlářský nůž"], correct: 1 },
    { q: "Jaký tvar má většina klasických podkov?", options: ["Čtverec", "U tvar", "V tvar"], correct: 1 },
    { q: "Jaký je znak špatně přibité podkovy?", options: ["Kůň kulhá", "Kůň více pije", "Kůň méně spí"], correct: 0 },
    { q: "Jak se nazývá část podkovy, která je v kontaktu se zemí?", options: ["Podrážka", "Běhoun", "Zemní plocha"], correct: 2 },
    { q: "Co je „podkovářská kovadlina“?", options: ["Stojan na koně", "Kovadlina pro tvarování podkov", "Držák na hřebíky"], correct: 1 },
    { q: "Jaký je hlavní účel „kopytního nože“?", options: ["Seříznutí přerostlé stěny a střelky", "Vytahování hřebíků", "Broušení podkov"], correct: 0 },
    { q: "Jak se pozná, že podkova potřebuje vyměnit?", options: ["Je pokrytá blátem", "Je opotřebovaná nebo se uvolňuje", "Má tmavší barvu"], correct: 1 },
    { q: "Jak se říká procesu přibíjení podkovy na kopyto?", options: ["Podkování", "Sedlání", "Kování kovu"], correct: 0 },
  ],
  trener: [
    { q: "Jaký je hlavní cíl základního výcviku mladého koně?", options: ["Zvýšit rychlost", "Naučit poslušnosti a práci s člověkem", "Připravit na závody během prvního měsíce"], correct: 1 },
    { q: "Co je to „lonžování“?", options: ["Krmení koně z ruky", "Pohybování koně na kruhu na dlouhém provaze", "Masážní technika"], correct: 1 },
    { q: "Jaký je typický začátek tréninku dostihového koně?", options: ["Dlouhé klidné klusání pro kondici", "Okamžité sprinty na maximum", "Skákání přes překážky"], correct: 0 },
    { q: "Jaký je účel „cool down“ po tréninku?", options: ["Uklidnit srdeční frekvenci a svaly", "Zlepšit chuť k jídlu", "Zpevnit kopyta"], correct: 0 },
    { q: "Co znamená pojem „gymnastické skákání“?", options: ["Skoky ve sportovní gymnastice", "Systém menších skoků pro zlepšení rovnováhy koně", "Protahovací cviky pro jezdce"], correct: 1 },
    { q: "Jaký je základní prvek westernového ježdění?", options: ["Piafa", "Sliding stop", "Pirueta na zadních"], correct: 1 },
    { q: "Co je to „handicap“ v dostizích?", options: ["Zdravotní omezení koně", "Záměrná zátěž (hmotnost navíc) pro vyrovnání šancí", "Chybný krok během startu"], correct: 1 },
    { q: "Jaký je hlavní účel drezurního tréninku?", options: ["Rozvoj poslušnosti, rovnováhy a pružnosti", "Zvýšení rychlosti", "Naučení skoku přes překážky"], correct: 0 },
    { q: "Jak se nazývá práce koně s dobytkem ve westernu?", options: ["Cutting", "Cross-country", "Eventing"], correct: 0 },
    { q: "Jaký je správný postup při učení koně novým cvikům?", options: ["Trpělivost, opakování, postupné zvyšování obtížnosti", "Náhlé změny a tvrdé tresty", "Krátké a zmatené pokyny"], correct: 0 },
    { q: "Kdy je nejlepší začít s intenzivním tréninkem dostihového koně?", options: ["Ve 2–3 letech", "V 6 měsících", "Po 10. roce věku"], correct: 0 },
    { q: "Jaký je účel „cvalové práce“ u sportovních koní?", options: ["Zlepšení kondice a rovnováhy", "Uklidnění koně", "Učení stání na místě"], correct: 0 },
    { q: "Jak se nazývá disciplína, kde kůň projíždí vzor mezi barely?", options: ["Barrel racing", "Trail", "Pole bending"], correct: 0 },
    { q: "Co znamená „startovací box“ u dostihů?", options: ["Skříň na jezdecké vybavení", "Zařízení pro správný a rovný start koní", "Tréninková ohrada"], correct: 1 },
    { q: "Jaký je hlavní cíl při práci ze země (groundwork)?", options: ["Vybudovat respekt a důvěru", "Zvýšit rychlost", "Naučit koně skákat"], correct: 0 },
    { q: "Jaký je účel tzv. intervalového tréninku?", options: ["Střídání zátěže a odpočinku pro lepší kondici", "Cvičení jen jednou týdně", "Krmení koně v přestávkách"], correct: 0 },
    { q: "Jaký je správný způsob odměňování koně při výcviku?", options: ["Pamlsky, pochvala hlasem nebo pohlazení", "Ignorování úspěchu", "Zvýšená fyzická zátěž"], correct: 0 },
    { q: "Co je to „reining“?", options: ["Drezurní disciplína westernového ježdění", "Dostih přes překážky", "Dlouhý klus na oválu"], correct: 0 },
    { q: "Co znamená „lead change“?", options: ["Kůň mění vedoucí nohu ve cvalu", "Kůň přechází z klusu do kroku", "Kůň mění směr pohledu"], correct: 0 },
    { q: "Jaký je účel tzv. cross-trainingu u koní?", options: ["Zapojení různých disciplín pro komplexní rozvoj", "Trénink pouze v jedné disciplíně", "Krmení různými typy ovsa"], correct: 0 },
  ],
};
